[project]
name = "newfamily"
version = "0.1.0"
description = "just for love"
readme = "README.md"
authors = [
    { name = "Cherry Fu", email = "me@dgct.cc" }
]
requires-python = ">=3.12"
dependencies = [
    "flet>=0.80.0",
    "flet-pages>=0.0.2",
]

[tool.uv]
package = false
